[[main]]
    name = 'Home'
    identifier = "home"
    pre = "bi bi-house-fill"
    pageRef = '/'
    weight = 10

[[main]]
    name = 'Blog'
    identifier = "blog"
    pre = "bi bi-file-post"
    pageRef = '/blog'
    weight = 20