[[main]]
    name = '首页'
    identifier = "home"
    pre = "bi bi-house-fill"
    pageRef = '/'
    weight = 10

[[main]]
    name = '博客'
    identifier = "blog"
    pre = "bi bi-file-post"
    pageRef = '/blog'
    weight = 20