baseURL = 'https://genway.com.cn/'
theme = 'hugo-theme-walden'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[pagination]
  disableAliases = false
  pagerSize = 12
  path = 'page'

[params]
  multiLingual = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.129.0"
