title = '瓦尔登湖'

contentDir = 'content/zh'
languageName = '简体中文'
languageCode = 'zh-Hans-CN'

copyright = '版权所有'

weight = 2

[params]
    author = 'Homecat'
    description = '雨花烟月此时逢，台殿虚无古寺中。莫问六朝何事业，万家砧杵弄秋风。'