title = 'Walden'

languageName = 'EN'
languageCode = 'en-US'

copyright = 'All rights reserved'

weight = 1


[params]
    author = 'Homecat'
    bio = 'Like a bridge over the troubled water, I will lay me down.'






