[[main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[[main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

[[main]]
    name = 'Document'
    pageRef = '/document'
    weight = 30